version: "3.8"

services:
  alexa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alexa-addon
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./homeassistant/config:/config
      - ./homeassistant/addon:/data
    restart: unless-stopped
